# Generated by Django 2.2.7 on 2020-08-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_auto_20200821_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='side',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
