# Generated by Django 2.2.7 on 2020-08-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_post_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='side',
            field=models.CharField(choices=[('Left', 'Left'), ('Center', 'Center'), ('Right', 'Right')], max_length=6),
        ),
    ]
