# Generated by Django 2.2.7 on 2020-08-21 05:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0005_auto_20200821_1040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='LPost',
        ),
    ]
